### ISSUE TITLE
초등학교 목록 크롤링 추가

### ISSUE THREAD

**Issue by hyeonski** [hyeonski/elementary_crawl#8]
전국 초등학교를 school 테이블에 저장할 수 있도록 초등학교 목록을 크롤링합니다.
데이터는 나이스 OPEN API에 xml 또는 json 형태로 요청하여 가져옵니다.

### 데이터 요청 방법
```
GET https://open.neis.go.kr/hub/schoolInfo

params:
 - KEY: API 인증키
 - Type: 데이터 포맷 (xml or json)
 - pSize: 페이지 당 데이터 개수
 - pIndex: 페이지 번호
 - SCHUL_KND_SC_NM: 학교 종류(초등학교 고정)
```
자세한 정보는 [나이스 Open API 학교기본정보 데이터셋 상세](https://open.neis.go.kr/portal/data/service/selectServicePage.do?page=1&rows=10&sortColumn=&sortDirection=&infId=OPEN17020190531110010104913&infSeq=2&cateId=A0001)에서 확인 가능
